// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Dra. Ana Paula - Neuropediatra e Pediatra",
  description: "Especialista em Neuropediatria e Pediatria. Cuidado especializado para o desenvolvimento neurológico infantil, diagnóstico e tratamento do TEA (Transtorno do Espectro Autista).",
  keywords: "neuropediatra, pediatra, TEA, autismo, desenvolvimento infantil, neurologia pediátrica",
  authors: [{ name: "Dra. Ana Paula" }],
  openGraph: {
    title: "Dra. Ana Paula - Neuropediatra e Pediatra",
    description: "Especialista em Neuropediatria e Pediatria. Cuidado especializado para o desenvolvimento neurológico infantil.",
    type: "website",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}